### ISSUE TITLE
Pronouns

### ISSUE THREAD

**Issue by Ellii13** [arimgibson/Deadname-Remover#120]
u could ad a feature that also changes your pronouns in things like emails or similar stuff.
Also more languages would be very usefull then

**Comment by Diyamund** [comment]
This is confusing because it would replace other pronouns like if there was a person who identified as male but you were MtF, wouldn't it replace him with her, his with her's, etc. ?

**Comment by MachCoyote** [comment]
> u could ad a feature that also changes your pronouns in things like emails or similar stuff.
> Also more languages would be very usefull then
That would require detection of context, which is harder than it sound so idk if that would be possible

**Comment by arimgibson** [comment]
Hi @Ellii13, thanks for the suggestions!

Regarding pronouns, as @aubymori pointed out, it's unfortunately not practical. See #22, and feel free to leave additional feedback there.

Regarding other languages, would that be to have the extension's text be in multiple languages? That would be possible to implement and something I can keep in mind! To be transparent, it falls low on my current priority list but I do see the benefit of eventually implementing it.

I'm going to close this issue as duplicate, but I will definitely keep the additional languages suggestion in mind. I'll add it to my todo list to create an issue specifically for additional languages
