### ISSUE TITLE
Hi, I'd like to suggest a feature :)

### ISSUE THREAD

**Issue by reesespuffs420** [arimgibson/Deadname-Remover#143]
I would like to suggest adding an option to add more names. I have my name in and it works but I was wondering if there was a way I could also add my friends names in. So, my deadname is removed but I want to also remove my friend's deadnames.

**Comment by TheStarlitBlade** [comment]
> I would like to suggest adding an option to add more names. I have my name in and it works but I was wondering if there was a way I could also add my friends names in. So, my deadname is removed but I want to also remove my friend's deadnames.

Multiple names would also be great if you have nicknames based on your deadname.

**Comment by AriGibson** [comment]
Hi @reesespuffs420 and @TheStarlitBlade  ! Sorry for the late response, I'm in the slow process of trying to clear out some of these issues that have been neglected.

This is actually already a feature, albeit a slightly hidden one. Check out #234 for some more infomation 😄 . If you need more help regarding this feature specifically, add a comment there and feel free to tag me using `@arigibson`

cc: @Gusted, this one can be closed 😀
