### ISSUE TITLE
Capital K's

### ISSUE THREAD

**Issue by mars-the-lad** [arimgibson/Deadname-Remover#20]
I have a really common last name (King) so when the tool sees it in any capacity, it capitalizes the K. like breaking becomes breaKing, cooking becomes cooKing, stuff like that. ive really only noticed it in youtube thumbnails, but i also haven't been using the tool for very long to notice if it happens other places. It's not a huge issue, but just something i noticed.

**Comment by arimgibson** [comment]
_Excuse my brevity as I catch up on a whole lot of issues that need to be reviewed_

Case matching is set to be implemented in version 2.0.0, which should resolve this. v2 also introduced word boundaries, so it'll only replace the name if it's a word by it's own

Keeping issue open until v2 release

**Comment by arimgibson** [comment]
Actually, I take that back. In order to reduce the insane amount of issues I have to go through, I'm going to close issues that are currently covered
