### ISSUE TITLE
Suggestion: Auto-Enabling/Disabling on Certain Websites

### ISSUE THREAD

**Issue by evieamity** [arimgibson/Deadname-Remover#219]
Hiya! I'm loving this extension, and it's been really helpful with avoiding dysphoria from my deadname.

I would suggest adding a feature that auto-enables or auto-disables the deadname remover when you're on a certain website. Like for example, making it so that if I go to gmail.com it automatically enables it and if I go to youtube.com it automatically disables it.

This would really help, as for some websites, I will never have a chance of seeing my deadname but may see other people who have it. This way you would less often get scenarios where someone had the same name as your deadname get changed to your preferred name.

**Comment by TogoorooDev** [comment]
This is an old issue, but it seems very useful. I'll try and work on this.

**Comment by arimgibson** [comment]
Thanks for the suggestion @evieamity ! Merging this into #520 ; hoping to implement this in version 2.0,0
