### ISSUE TITLE
The Future of Deadname Remover (Discussion)

### ISSUE THREAD

**Issue by WillHayCode** [arimgibson/Deadname-Remover#227]
Hi team! I'm currently moving house, but I'm hoping to get a new version up by the end of the month. The move is going to give me a couple more free hours every day, and I would like to be more active on this again.

That said, it's really not fair to anyone that updates are entirely dependent on my personal schedule. There's a few ways we can mitigate this without giving any one person total control of the project, and I thought it was worth discussing.

One options is that we either find (or found) a small LGBT organisation to manage this aspect, and the members of that organisation would be responsible for pushing updates to the web stores.

Another option is that we set up [Group Publishing](https://developer.chrome.com/webstore/group-publishers) and add other trusted accounts to the plugin for the Chrome and Firefox web stores, then updates can be pushed by multiple people.

Any ideas and suggestions welcome. Thank you all for contributing to Deadname Remover. We recently hit **thirty thousand** Chrome installs.

**Comment by WillHayCode** [comment]
@Gusted I'm a little out of the loop on who is actively contributing at the moment, but if you wanted to tag anyone who might have input please do.

**Comment by Gusted** [comment]
Hey!

The `Group Publishing` option seems to be an handy option, as it will be under control of experienced/trusted developers that have knowledge about extensions.
On the other hand an LGBT organisation is also an good idea, to have have a better integration within the LGBT community.

CC @AriGibson @EmilyLove26

**Comment by AriGibson** [comment]
I'm really loving the Group Publishing idea; I think this is something I'd want to contribute to the maintainence to. I'm not sure what organization would like to take this on; I'm not familiar with any software organizations that focus on queer issues. I also generally like the idea of code unaffiliated with organizations or companies.

A tad bit unrelated, but @Gusted , is it alright if I go through issues and tag you on ones that can probably close? I don't want to overstep but I also want to be helpful where possible with my coding free time.

**Comment by Gusted** [comment]
> A tad bit unrelated, but @Gusted , is it alright if I go through issues and tag you on ones that can probably close? I don't want to overstep but I also want to be helpful where possible with my coding free time.

Sure

**Comment by No-Known-Alias** [comment]
Hi, I am Really loving this project, and looking forward to see updates to it, while I can't code, I was wondering if there is a way to have the deadname removed while in a google meet. My school is using them, and it would help the teachers remember. If there is not a way to do it, or it is implemented and can't find it, I am so sorry for bothering you. Either way, group publishing could make it easier to push out updates and I like the idea. Sorry that I haven't responded sooner, but I just got this! Thank you for making it and have a nice day!

**Comment by WillHayCode** [comment]
Sounds like everyone is generally in agreement - I'll set up group publishing this weekend.

@No-Known-Alias - Do you mean removed for other people, or for yourself? Removing for other people is probably something that we can't realistically implement unfortunately, but if it isn't removing the name for yourself that's a bug we'll look into.

**Comment by No-Known-Alias** [comment]
Oh, ok I was just wondering if that was possible, thank you for letting me know! Either way this is a great thing to have, Thank you for making it!

**Comment by EmilyLove26** [comment]
I'm no where near knowledgeable enough to be eligible for group publishing. I can barely modify the existing code as it. I appreciate the thought though <3

**Comment by WillHayCode** [comment]
Genuine apologies for the delay - I'm still adjusting to the time management of full time work.

We now have a Google Group! https://groups.google.com/u/3/g/deadname-remover

I've set DNR to use the group for publishing, so if you join there I can give you the permissions to upload new versions.
