### ISSUE TITLE
Suggestion: Toggle on/off and whitelist

### ISSUE THREAD

**Issue by Xorlac** [arimgibson/Deadname-Remover#23]
Two features that'd be pretty useful are a way to quickly toggle it on and off, and have an option to whitelist certain sites/domains so no names are changed there

**Comment by WillHayCode** [comment]
Thanks for the suggestions! Toggle functionality has been added in the newest update (1.2), and whitelisting is very much on the roadmap

**Comment by 3n-k1** [comment]
@WillHayCode i'd love to try and implement whitelisting if you aren't already working on it :)

**Comment by WillHayCode** [comment]
@3n-k1 - Please! I've not had the energy to actively work on this for a while, so all contributions are welcome and valuable.

**Comment by 3n-k1** [comment]
@WillHayCode awesome! i'm not super profficient with js, and i've never used typescript, so it might take me a bit :p

**Comment by arimgibson** [comment]
Closing this one as I've started consolidating this request into #520, it's a popular one! Hoping to release this with a version 2.0.0 @Xorlac, which I'm hoping to finish in the next couple weeks. Thanks for the suggestion!

See #520
