### ISSUE TITLE
MY NAME

### ISSUE THREAD

**Issue by leodiamod** [arimgibson/Deadname-Remover#236]
I CANT CANGER IT BACK IM MAD AND  ANGRY

**Comment by AriGibson** [comment]
Hi @leodiamod !

I'd need more information to understand what's going on, but in the meantime, you can always uninstall the extension and it'll go back to normal.

If you have some more information, let me know within a week or I'll plan on marking this issue for deletion :)

~ Ari

**Comment by arimgibson** [comment]
Closing because of lack of reply/context
