### ISSUE TITLE
Feature request: Formatting of the name replacement.

### ISSUE THREAD

**Issue by taminaminam** [arimgibson/Deadname-Remover#237]
I haven't used this extension for long, but I already love it. What I would like though is a feature to enter custom formatting for the replacement (or even just html formatting) so I could have the name in _Italics_, since I don't wanna accidentally mix up things by reading off the wrong name if I'm reading off something to someone.

**Comment by arimgibson** [comment]
Sorry for the late follow up! Excuse the brevity and templated replies as I clear through tons of GitHub issues.

Will be covered in next release thru ability to toggle highlighting behind name, but I love the italics idea! Def considering
