### ISSUE TITLE
Deadname remover not working

### ISSUE THREAD

**Issue by Leonkazu** [arimgibson/Deadname-Remover#238]
deadass, on any website i go on it doesnt work, it always says my deadname. can someone help? this is getting annoying its been two weeks

**Comment by Epsilqn** [comment]
Hi! Can you provide some more information? You need to enable the remover, and configure the settings. If you could provide screenshots of your config that'd be great!

**Comment by arimgibson** [comment]
Closing due to age without reporter reply -- feel free to open another issue if you're still having this problem!
