### ISSUE TITLE
Add feature for full and short deadnames and their replacements

### ISSUE THREAD

**Issue by Plush-pixel** [arimgibson/Deadname-Remover#319]
It's always nice to se my new name replaced when looking at my messages, but I can only replace either the short or the full version of my deadname, so it would be nice if you could write your full and short deadname and what they should be replaced with accordingly, thanks in advanced.

**Comment by thatonebiemo** [comment]
Yea I'm having the same issue.

**Comment by arimgibson** [comment]
Got this covered in the version 2.0.0 release, which I'm hoping to ship out within the next few weeks. Thanks for your suggestion!!
