### ISSUE TITLE
Changing entire text block, instead of just name on Google Classroom

### ISSUE THREAD

**Issue by ERmilburn02** [arimgibson/Deadname-Remover#339]
### On Google Classroom, the extension is changing the entire message to the name, instead of just changing the name
Disabled
![image](https://user-images.githubusercontent.com/61363431/111458576-7dd16200-8711-11eb-9353-03f992f6e81e.png)
Enabled
![image](https://user-images.githubusercontent.com/61363431/111458683-a3f70200-8711-11eb-8f42-901cb477939b.png)

Google Chrome 89.0.4389.90 (Official Build) (64-bit) (cohort: 89_Win_72)
Windows 10 OS Version 2009 (Build 19042.867)

**Comment by trqzh** [comment]
Same behaviour on Outlook.
![image](https://user-images.githubusercontent.com/62384273/119860047-ddb46800-bf0d-11eb-910a-d8068b31e2f7.png)
