### ISSUE TITLE
Whitelist for Websites

### ISSUE THREAD

**Issue by lilymnky-F** [arimgibson/Deadname-Remover#345]
It would be appreciated if there could be a toggle to have a whitelist. Current I have to switch it on and off whenever I' using non-school related sites, which is really the only time I want it on. It would be appriciated to have a whitelist option for sites that it runs on.

**Comment by cid-chan** [comment]
Yeah. This plugin may even out me on email-responses as it also replaces my name in editable the rich-text-editor of my webmailer.

**Comment by warpedtour08** [comment]
this is a built-in setting on (chrome-based, maybe others as well?) browsers !! go to settings > extensions > manage extensions > deadname remover > details > site access, and set it to "on specific sites". then, type in whichever sites u need, and badabing badaboom! it works !!  tbh, i think that having a /blacklist/ would be useful asf, but, unfortunately, chrome does Not have a feature for that 😔

**Comment by arimgibson** [comment]
Sorry for the late follow up! Excuse the brevity and templated replies as I clear through tons of GitHub issues.

Adding both URL whitelist and blacklist features to the next release, thanks for the suggestion!
