### ISSUE TITLE
Exclude words?

### ISSUE THREAD

**Issue by 2minwia** [arimgibson/Deadname-Remover#40]
if an actual word happens to include your deadname, some silly things can happen.
for example, if your deadname is jack:
jacket = [deadname replaced here]et
headphone jack = headphone [deadname replaced here]
an option to replace words, or multiple combined words (in the case of headphone jack) would make this a lot less confusing?
...alternatively, maybe an option to exclude anything that isnt [deadname] followed by a comma, dash, or similar?

(unrelated to the actual issue, but huge props to the dev team for making this extension, has made me feel a lot better just.. browsing the internet like normal. thank you all so much!!!!)

**Comment by arimgibson** [comment]
Thanks for the suggestion @2minwia, and sorry for getting to this so late! This is covered with new replacing logic that will be introduced in version 2.0.0, which I'm hoping to ship out to users within the next few weeks 😄
