### ISSUE TITLE
I'm reporting a bug

### ISSUE THREAD

**Issue by MelonMel14** [arimgibson/Deadname-Remover#421]
I watch some Youtube video's with the title as my deadname (they're not referring to me, my deadname is pretty common.) and I exit out of them and open another video that doesn't have my deadname in the title, but for some reason, the deadname is in there when it really isn't. and it repeats until I exit my browser and restart my computer, I'm not really good at explaining things but I hope you can find some way to fix that!

**Comment by arimgibson** [comment]
_Excuse my brevity as I catch up on a whole lot of issues that need to be reviewed_

Thanks for the bug report @MelonMel14 ! I just responded to the same issue in #20; if you have more comments, feel free to move them over there :)
