### ISSUE TITLE
Something is wrong with the extension

### ISSUE THREAD

**Issue by honeiiboii** [arimgibson/Deadname-Remover#46]
Hey mate,
I've been using this extension for a few days and, for some reason, it doesn't work on the google home page and it wont let me access the permissions. 

Thanks in advance.

**Comment by WillHayCode** [comment]
Hi @honeiiboii - There's a new version (1.2) of the extension available for Chrome and Firefox. Are you still experiencing this issue with the update?

**Comment by arimgibson** [comment]
Closing due to age without reporter reply -- feel free to open another issue if you're still having this problem!
