### ISSUE TITLE
Can you have a feature to turn it off for google docs?

### ISSUE THREAD

**Issue by magdelenn** [arimgibson/Deadname-Remover#461]
I need to write my deadname in for school stuff and it automatically replaces it with my real name which kinda bugs out and looks weird when im typing my thing

thank you !! i just need this as an optional thing so it doesnt throw me off 

i love this extension though !! and thanks for making it open source !!

**Comment by arimgibson** [comment]
Sorry for the late follow up! Excuse the brevity and templated replies as I clear through tons of GitHub issues.

Will be covered in next release thru ability to disable on certain URLs :)

**Comment by magdelenn** [comment]
> Sorry for the late follow up! Excuse the brevity and templated replies as I clear through tons of GitHub issues.
> 
> Will be covered in next release thru ability to disable on certain URLs :)

I personally don't need that feature any more, but it's going to be super helpful to those who do. Thank you so much for maintaining this awesome project :D
