### ISSUE TITLE
Suggestion: Name variations

### ISSUE THREAD

**Issue by lukasong** [arimgibson/Deadname-Remover#489]
Some dead-names have variations (ex. Alexander, Alexandra both are used for Alex). Perhaps a list (CSV?) for alternatives to replace. If there is a want for this, I can implement it and add a pull request ^~^

**Comment by arimgibson** [comment]
Sorry for the late follow up! Excuse the brevity and templated replies as I clear through tons of GitHub issues.

Will be covered in next release thru ability to specify multiple names to replace. In the future though, I can definitely see it being helpful to be able to replace certain deadnames with certain preferred names. That'll probably be a bit down the road
