### ISSUE TITLE
settings will open when first opening firefox sometimes(?)

### ISSUE THREAD

**Issue by eluna7** [arimgibson/Deadname-Remover#525]
this isnt a large issue at all and its not consistent, i haven't tested very much but i cannot make this consistently happen. not like its an issue at all, deadnames stay hidden unless purposefully opened, i just dont like getting flashbanged by the settings page x_x

i saw this was an issue with chrome before when looking at other issues, but i use exclusively firefox.

great extension, makes it a little bit easier to do school work :)

**Comment by arimgibson** [comment]
Thanks for reporting this @eluna7 ! I know you mentioned seeing some other issues where people were describing this issue in Chrome; not sure if you saw but we've been talking Firefox as well at #35  :) closing this one as a duplicate, but feel free to write there if you have anything to add to that discussion!! Glad you've found the extension useful :heart_eyes_cat:
