### ISSUE TITLE
Deadname being replaced on other's people names

### ISSUE THREAD

**Issue by OlliePoyo** [arimgibson/Deadname-Remover#554]
When a deadname is to be displayed, it is replaced even if the last name is not a match. This results in instances of other people's names being identified as a deadname instance and being replaced

Ex:
Dead Name: Joe
Dead Last Name: Doe
Name: Joane
Dead Last Name: Doe

Original text: Joe Smith
Changed text: Joanne Smith

**Comment by arimgibson** [comment]
Hi @OlliePoyo and thanks for the feedback! This is a pretty common issue that gets reported, with good reason.

I just wrote up a good explanation on this in issue #207; going to close as duplicate but please check out my explanation there and pass along any ideas or feedback in that issue :relaxed:
