### ISSUE TITLE
lowercase names

### ISSUE THREAD

**Issue by roteroro** [arimgibson/Deadname-Remover#60]
hi! i don't know if it's a mistake on my part or anything, but it seems like it only removes the deadname i type in, meaning only uppercase. in casual chatting people tend to use my name in lowercase so it still shows up as the name i don't prefer. if you could add that or tell me how to do that it'd be great!

**Comment by WillHayCode** [comment]
Hi @roteroro ! Are you still experience this bug in the newest version of the extension? (1.2)

**Comment by arimgibson** [comment]
Closing due to age without reporter reply -- feel free to open another issue if you're still having this problem! However, this should also be fixed with new logic in version 2.0.0 which is case-insensitive
