### ISSUE TITLE
changes deadname on other people's name

### ISSUE THREAD

**Issue by alliephenix** [arimgibson/Deadname-Remover#82]
I install this for online classes and I have a professor with the same first name as my deadname, and it keeps changing his first name to my name.

**Comment by AriGibson** [comment]
Hi @alliephenix !

Unfortunately, there's no easy fix for this... I can definitely understand how that's annoying though. I wish I had a better answer to offer, but there isn't really a way to avoid this, at least one that i can think of. 😕

~ Ari

**Comment by arimgibson** [comment]
Merging this one in with #71
